// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7VhklRxDSxLx9z_ECiM9s7-dzSI9dA2k',
    appId: '1:562024769149:web:b6a047ea8a1f0e0628b314',
    messagingSenderId: '562024769149',
    projectId: 'dertortagi-276f4',
    authDomain: 'dertortagi-276f4.firebaseapp.com',
    databaseURL: 'https://dertortagi-276f4-default-rtdb.firebaseio.com',
    storageBucket: 'dertortagi-276f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFL7LAgzXm0z9WR3Vhwb7dJdpvMMiRaX0',
    appId: '1:562024769149:android:ea8adecd3e9fdc3328b314',
    messagingSenderId: '562024769149',
    projectId: 'dertortagi-276f4',
    databaseURL: 'https://dertortagi-276f4-default-rtdb.firebaseio.com',
    storageBucket: 'dertortagi-276f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYvijwZBqV8V7RahFSM1Th78KHEyrybv8',
    appId: '1:562024769149:ios:310e30bd46f1fbc428b314',
    messagingSenderId: '562024769149',
    projectId: 'dertortagi-276f4',
    databaseURL: 'https://dertortagi-276f4-default-rtdb.firebaseio.com',
    storageBucket: 'dertortagi-276f4.firebasestorage.app',
    iosBundleId: 'com.example.agor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYvijwZBqV8V7RahFSM1Th78KHEyrybv8',
    appId: '1:562024769149:ios:310e30bd46f1fbc428b314',
    messagingSenderId: '562024769149',
    projectId: 'dertortagi-276f4',
    databaseURL: 'https://dertortagi-276f4-default-rtdb.firebaseio.com',
    storageBucket: 'dertortagi-276f4.firebasestorage.app',
    iosBundleId: 'com.example.agor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7VhklRxDSxLx9z_ECiM9s7-dzSI9dA2k',
    appId: '1:562024769149:web:6220b2b378123c7328b314',
    messagingSenderId: '562024769149',
    projectId: 'dertortagi-276f4',
    authDomain: 'dertortagi-276f4.firebaseapp.com',
    databaseURL: 'https://dertortagi-276f4-default-rtdb.firebaseio.com',
    storageBucket: 'dertortagi-276f4.firebasestorage.app',
  );

}